create sequence customerNumber_id_sequence start 1 increment 1;
create sequence hibernate_sequence start 1 increment 1;
create sequence orderingNumber_id_sequence start 1 increment 1;
create sequence orderPositionNumber_id_sequence start 1 increment 1;
create sequence pizzaNumber_id_sequence start 1 increment 1;
create table Customer (id int8 not null, city varchar(255), postcode int4, street varchar(255), name varchar(255), version int8, primary key (id));
create table Customer_Ordering (Customer_id int8 not null, orderingList_id int8 not null);
create table Ordering (id int8 not null, version int8, primary key (id));
create table Ordering_OrderPosition (Ordering_id int8 not null, orderPositionList_id int8 not null);
create table OrderPosition (id int8 not null, qty int4 not null, version int8, pizza_id int8, primary key (id));
create table Pizza (id int8 not null, name varchar(255), price float8 not null, version int8, primary key (id));
create table UserLogin (id int8 not null, password varchar(255), role varchar(255), username varchar(255), primary key (id));
alter table if exists Customer_Ordering add constraint UK_42orm0cvlc0vd6h290eliytl unique (orderingList_id);
alter table if exists Ordering_OrderPosition add constraint UK_ne11wady7qt6ex797d8mqfxmt unique (orderPositionList_id);
alter table if exists Customer_Ordering add constraint FKo4q3f0osufnvkfhxp229q2p2j foreign key (orderingList_id) references Ordering;
alter table if exists Customer_Ordering add constraint FK1h41v8e1d0ejnmdf63oo5el5e foreign key (Customer_id) references Customer;
alter table if exists Ordering_OrderPosition add constraint FKn2uqwik385lt4hyig44xky0p8 foreign key (orderPositionList_id) references OrderPosition;
alter table if exists Ordering_OrderPosition add constraint FK84un56apqvfhlvnocjl7qj9pd foreign key (Ordering_id) references Ordering;
alter table if exists OrderPosition add constraint FKtektgup8e8rcvrlcd1f1hw4ie foreign key (pizza_id) references Pizza;
insert into pizza (name, price) values ('Margherita', 5.50);
insert into pizza (name, price) values ('Salami', 6.50);
insert into pizza (name, price) values ('Hawaii', 7.50);
insert into pizza (name, price) values ('Vegetarian', 8.50);
